---
# ============================================================= PLAY =====================================================
# This playbook will create a virtual network in Azure
# Inputs:

  # the name of this playbook. You see this back in the default logging
- name: Azure Create Virtual Network

  # There is no concepts of hosts in a public cloud. We use localhost to specify that this playbook runs from the
  # Ansible execution host (engine or tower).
  hosts: localhost
  
  # likewise, since we use the Azure API, there is no concept of a connection. Thus we specify local
  connection: local
  
  # specify which collections are being used in this playbook
  collections:
  - azure.azcollection
  
  # this is a way to specify files that contain vars
  vars_files:
    # here we include a var file from a sub directory "files"
    files/azure_vars
  
   # We now start the tasks that must be executed in order
  tasks:
    
  - name: create Azure virtual network {{ vnet }} for project {{ project }}
    azure_rm_virtualnetwork:
      name: '{{ project }}'
      resource_group: '{{ project }}'
      address_prefixes_cidr: '10.{{ vnet }}.0.0/16'
      state: present
  
  - name: create Azure subnet {{ subnet }} in virtual network {{ vnet }} for project {{ project }}
    azure_rm_subnet:
      name: '{{ project }}'
      resource_group: '{{ project }}'
      virtual_network_name: '{{ project }}'
      address_prefix_cidr: '10.{{ vnet }}.{{ subnet }}.0/24'
      state: present
